language: rust
cache: cargo

rust:
  - stable
  - beta
  - nightly

os:
  - linux
  - osx

matrix:
  allow_failures:
    - rust: nightly

script:
  - rustc --version
  - cargo --version
  - cargo build --verbose
  - cargo test --verbose
  - cargo doc --verbose
