[package]
name = "glsl-include"
version = "0.1.0"
authors = ["Justin Shrake <justinshrake@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
regex = "0.2"
lazy_static = "1.0.0"

[dev-dependencies]
indoc = "0.2"
